server:
  port: 8080

spring:
  application:
    name: devices-app
  datasource:
    url: jdbc:mysql://localhost:3306/devices?createDatabaseIfNotExist=true&useSSL=false
    password: app
    username: app
    datasource:
      initialization-mode: always
    hikari:
      maxLifetime: 140000
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write_dates_as_timestamps: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    generate-ddl: true
  output:
    ansi:
      enabled: ALWAYS